services:
  db:
    # networks:
    #   - api_network
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: mini_booking_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mini_booking}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-mini_booking}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  # api:
  #   networks:
  #     - api_network
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: mini_booking_api
  #   restart: unless-stopped
  #   ports:
  #     - "5003:5003"
  #   env_file:
  #     - .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/mini_booking?schema=public

volumes:
  postgres_data:

# networks:
#   api_network:
#     name: api_network
